AWSTemplateFormatVersion: '2010-09-09'
Description: CFT for DynamoDB LogEntries table setup for ATA Week 13 activities

Resources:
  LogEntries:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: "LogEntries"
      AttributeDefinitions: 
        - AttributeName: "log_level"
          AttributeType: "S"
        - AttributeName: "time_stamp"
          AttributeType: "S"
      BillingMode: "PAY_PER_REQUEST"
      ContributorInsightsSpecification: 
        Enabled: false
      KeySchema: 
        - AttributeName: "log_level"
          KeyType: HASH
        - AttributeName: "time_stamp"
          KeyType: RANGE
      PointInTimeRecoverySpecification: 
        PointInTimeRecoveryEnabled: false
      TableClass: "STANDARD"
      Tags: 
        - Key: Week
          Value: 13
        - Key: CourseName
          Value: ata
        - Key: InstructorMade
          Value: true
  