AWSTemplateFormatVersion: '2010-09-09'
Description: CFT for DynamoDB TaskTracker table setup for ATA Week 13 activities

Resources:
  TaskTracker:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: "TaskTracker"
      AttributeDefinitions: 
        - AttributeName: "job_id"
          AttributeType: "S"
      BillingMode: "PAY_PER_REQUEST"
      ContributorInsightsSpecification: 
        Enabled: false
      KeySchema: 
        - AttributeName: "job_id"
          KeyType: HASH
      PointInTimeRecoverySpecification: 
        PointInTimeRecoveryEnabled: false
      TableClass: "STANDARD"
      Tags: 
        - Key: Week
          Value: 13
        - Key: CourseName
          Value: ata
        - Key: InstructorMade
          Value: true
  