AWSTemplateFormatVersion: '2010-09-09'
Description: CFT for DynamoDB TaskTracker table setup for ATA Week 13 activities

Resources:
  DynamoDBDeleteIteratorsEvents:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: "DynamoDBDeleteIterators-Events"
      AttributeDefinitions: 
        - AttributeName: "id"
          AttributeType: "S"
      BillingMode: "PAY_PER_REQUEST"
      ContributorInsightsSpecification: 
        Enabled: false
      KeySchema: 
        - AttributeName: "id"
          KeyType: HASH
      PointInTimeRecoverySpecification: 
        PointInTimeRecoveryEnabled: false
      TableClass: "STANDARD"
      Tags: 
        - Key: Week
          Value: 13
        - Key: CourseName
          Value: ata
        - Key: InstructorMade
          Value: true
  DynamoDBDeleteIteratorsMembers:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: "DynamoDBDeleteIterators-Members"
      AttributeDefinitions: 
        - AttributeName: "id"
          AttributeType: "S"
      BillingMode: "PAY_PER_REQUEST"
      ContributorInsightsSpecification: 
        Enabled: false
      KeySchema: 
        - AttributeName: "id"
          KeyType: HASH
      PointInTimeRecoverySpecification: 
        PointInTimeRecoveryEnabled: false
      TableClass: "STANDARD"
      Tags: 
        - Key: Week
          Value: 13
        - Key: CourseName
          Value: ata
        - Key: InstructorMade
          Value: true
  DynamoDBDeleteIteratorsInvites:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: "DynamoDBDeleteIterators-Invites"
      AttributeDefinitions: 
        - AttributeName: "eventId"
          AttributeType: "S"
        - AttributeName: "memberId"
          AttributeType: "S"
      BillingMode: "PAY_PER_REQUEST"
      ContributorInsightsSpecification: 
        Enabled: false
      KeySchema: 
        - AttributeName: "eventId"
          KeyType: HASH
        - AttributeName: "memberId"
          KeyType: RANGE
      PointInTimeRecoverySpecification: 
        PointInTimeRecoveryEnabled: false
      TableClass: "STANDARD"
      Tags: 
        - Key: Week
          Value: 13
        - Key: CourseName
          Value: ata
        - Key: InstructorMade
          Value: true
  