Resources:
  ReceiptsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      "AttributeDefinitions":
        - "AttributeName": "receiptId"
          "AttributeType": "S"
        - "AttributeName": "timestamp"
          "AttributeType": "S"
      "KeySchema":
        - "AttributeName": "receiptId"
          "KeyType": "HASH"
        - "AttributeName": "timestamp"
          "KeyType": "RANGE"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: false
      BillingMode: PAY_PER_REQUEST
      TableName: "Receipts"
